apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  foo: "bar"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pre-delete-hook
  annotations:
    argocd.argoproj.io/hook: PreDelete
spec:
  template:
    spec:
      containers:
        - name: busybusy
          image: registry.k8s.io/busybox
          command: ["/bin/sh", "-c", "env"]
          envFrom:
            - configMapRef:
                name: test-config
      restartPolicy: Never
  backoffLimit: 4
