apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  foo: "bar"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pre-delete-hook
  annotations:
    argocd.argoproj.io/hook: PreDelete
spec:
  template:
    spec:
      containers:
        - name: busybusy
          image: busybox
          command: ["/bin/sh", "-c", "env", "&&", "sleep", "3600"]
          envFrom:
            - configMapRef:
                name: test-config
      restartPolicy: Never
  backoffLimit: 4
